In [2]:
import pandas as pd
data = pd.read_csv('Real_Estate.csv')

data.head()

,Transaction date,House age,Distance to the nearest MRT station,Number of convenience stores,Latitude,Longitude,House price of unit area
0,2012-09-02 16:42:30.519336,13.3,4082.0150,8,25.007059,121.561694,6.488673
1,2012-09-04 22:52:29.919544,35.5,274.0144,2,25.012148,121.546990,24.970725
2,2012-09-05 01:10:52.349449,1.1,1978.6710,10,25.003850,121.528336,26.694267
3,2012-09-05 13:26:01.189083,22.2,1055.0670,5,24.962887,121.482178,38.091638
4,2012-09-06 08:29:47.910523,8.5,967.4000,6,25.011037,121.479946,21.654710

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Transaction date                     414 non-null    object
 1   House age                            414 non-null    float64
 2   Distance to the nearest MRT station  414 non-null    float64
 3   Number of convenience stores         414 non-null    int64
 4   Latitude                             414 non-null    float64
 5   Longitude                            414 non-null    float64
 6   House price of unit area             414 non-null    float64
dtypes: float64(5), int64(1), object(1)
memory usage: 22.8+ KB

In [5]:
data.describe()

,House age,Distance to the nearest MRT station,Number of convenience stores,Latitude,Longitude,House price of unit area
count,414.000000,414.000000,414.000000,414.000000,414.000000,414.000000
mean,18.405072,1064.468233,4.265700,24.973605,121.520268,29.102149
std,11.757670,1196.749385,2.880498,0.024178,0.026989,15.750935
min,0.000000,23.382840,0.000000,24.932075,121.473888,0.000000
25%,9.900000,289.324800,2.000000,24.952422,121.496866,18.422493
50%,16.450000,506.114400,5.000000,24.974353,121.520912,30.394070
75%,30.375000,1454.279000,6.750000,24.994947,121.544676,40.615184
max,42.700000,6306.153000,10.000000,25.014578,121.565321,65.571716

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import datetime

# convert "Transaction date" to datetime and extract year and month
data['Transaction date'] = pd.to_datetime(data['Transaction date'])
data['Transaction year'] = data['Transaction date'].dt.year
data['Transaction month'] = data['Transaction date'].dt.month

data.head()
# data['Transaction date']

,Transaction date,House age,Distance to the nearest MRT station,Number of convenience stores,Latitude,Longitude,House price of unit area,Transaction year,Transaction month
0,2012-09-02 16:42:30.519336,13.3,4082.0150,8,25.007059,121.561694,6.488673,2012,9
1,2012-09-04 22:52:29.919544,35.5,274.0144,2,25.012148,121.546990,24.970725,2012,9
2,2012-09-05 01:10:52.349449,1.1,1978.6710,10,25.003850,121.528336,26.694267,2012,9
3,2012-09-05 13:26:01.189083,22.2,1055.0670,5,24.962887,121.482178,38.091638,2012,9
4,2012-09-06 08:29:47.910523,8.5,967.4000,6,25.011037,121.479946,21.654710,2012,9

In [9]:
# drop the original "Transaction date" as we've extracted relevant features
data = data.drop(columns=['Transaction date'])

# define features and target variable
X = data.drop('House price of unit area', axis=1)
y = data['House price of unit area']

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled.shape

(331, 7)

In [11]:
X_test_scaled

array([[-2.60865532e-01, -5.23525629e-01,  1.00053687e+00,
         6.57868263e-01,  1.62222330e+00,  7.24807300e-01,
        -5.06523035e-02],
       [-2.49461574e-02,  2.45603201e-01,  1.35895430e+00,
        -7.99567856e-01,  1.74069839e+00,  7.24807300e-01,
        -5.06523035e-02],
       [-1.06973196e+00, -6.72942804e-01, -1.14996770e+00,
         1.45816905e+00,  1.40793313e+00,  7.24807300e-01,
        -5.06523035e-02],
       [ 1.48325270e+00, -7.07913117e-01,  1.71737173e+00,
         1.55718472e+00,  1.72952866e+00,  7.24807300e-01,
         2.28779571e-01],
       [ 1.04511672e+00,  2.90886903e-01, -7.91550275e-01,
         1.12502065e+00,  3.61442874e-01,  7.24807300e-01,
        -5.06523035e-02],
       [-9.85475038e-01, -4.98697166e-01, -7.47154158e-02,
        -1.55786181e+00, -1.71263737e+00, -1.37967705e+00,
         1.06707519e+00],
       [ 1.60121239e+00,  3.19767702e-01, -1.14996770e+00,
        -4.22502481e-01,  1.94507237e-01,  7.24807300e-01,
        -8.88947926e-01],
       [-4.79933522e-01, -7.07913117e-01, -7.91550275e-01,
        -8.66361033e-01,  6.34645936e-01, -1.37967705e+00,
         1.62593894e+00],
       [ 1.48325270e+00, -7.31869403e-01, -7.91550275e-01,
         9.80454866e-01, -4.55452414e-01, -1.37967705e+00,
         1.34650707e+00],
       [-9.01218119e-01,  2.24226194e+00, -4.33132845e-01,
         6.81244648e-01, -9.42037297e-01, -1.37967705e+00,
         1.06707519e+00],
       [ 1.39057009e+00, -6.49313616e-01, -7.91550275e-01,
        -5.58636929e-02, -1.73200520e+00, -1.37967705e+00,
         1.34650707e+00],
       [-2.18737072e-01, -8.17340994e-02,  1.35895430e+00,
         1.46348118e+00, -4.88808582e-01, -1.37967705e+00,
         1.62593894e+00],
       [-3.95676603e-01,  9.54665103e-01, -1.50838513e+00,
        -1.06206309e+00,  3.15135804e-01,  7.24807300e-01,
        -3.30084178e-01],
       [ 1.35686732e+00, -5.36907411e-01, -1.50838513e+00,
        -6.78411741e-01, -1.17052955e+00, -1.37967705e+00,
         1.06707519e+00],
       [-3.61973835e-01, -7.25222721e-01,  2.83702014e-01,
        -6.90110053e-02,  1.00461021e+00, -1.37967705e+00,
         1.62593894e+00],
       [-1.54157071e+00, -6.37867929e-01, -7.91550275e-01,
        -8.71076254e-01, -4.77998688e-01,  7.24807300e-01,
         2.28779571e-01],
       [ 1.35686732e+00, -8.05549375e-01, -1.14996770e+00,
        -1.09642280e+00,  1.38083652e+00, -1.37967705e+00,
         1.06707519e+00],
       [-3.78825219e-01, -2.85771459e-01, -1.14996770e+00,
        -1.15115277e-01,  4.00117478e-01,  7.24807300e-01,
        -6.09516052e-01],
       [-1.54157071e+00, -4.80768056e-01, -4.33132845e-01,
         4.25857268e-01, -2.12441070e-01,  7.24807300e-01,
        -5.06523035e-02],
       [ 1.09567087e+00, -4.56104839e-01,  1.00053687e+00,
        -1.70188808e+00,  1.60022452e-01, -1.37967705e+00,
         1.34650707e+00],
       [-1.09203077e-01, -4.80768056e-01,  1.00053687e+00,
         3.89727818e-01, -8.93145923e-01, -1.37967705e+00,
         1.34650707e+00],
       [-4.46230754e-01, -6.12487266e-01,  1.35895430e+00,
         2.35446495e-01, -1.36855991e+00, -1.37967705e+00,
         7.87643319e-01],
       [ 1.03669103e+00, -4.96113003e-01, -1.50838513e+00,
        -7.94031370e-01, -1.12305798e-01,  7.24807300e-01,
         2.28779571e-01],
       [ 6.15406430e-01, -4.80768056e-01, -1.50838513e+00,
        -8.54884503e-02, -4.42148138e-01, -1.37967705e+00,
         1.62593894e+00],
       [-1.17628769e-01,  8.97345597e-01,  2.83702014e-01,
        -1.28258847e+00,  1.25758845e+00,  7.24807300e-01,
        -3.30084178e-01],
       [ 2.86804444e-01, -3.82992829e-01,  1.00053687e+00,
        -1.03760011e+00,  1.02807994e+00,  7.24807300e-01,
         2.28779571e-01],
       [-6.99001512e-01,  1.33412577e+00, -1.14996770e+00,
        -9.45647996e-01,  1.24438113e+00,  7.24807300e-01,
        -8.88947926e-01],
       [-5.02232332e-02,  5.37427178e-01,  1.35895430e+00,
         4.30457279e-01, -1.72823945e+00, -1.37967705e+00,
         1.34650707e+00],
       [-1.06973196e+00, -5.63124156e-01,  1.35895430e+00,
         1.49211338e+00, -3.88469188e-01, -1.37967705e+00,
         1.34650707e+00],
       [ 1.81185469e+00,  1.43297204e-01,  1.35895430e+00,
        -4.79756546e-01,  9.22477143e-01,  7.24807300e-01,
        -1.44781167e+00],
       [-7.24278588e-01, -7.39090803e-01, -4.33132845e-01,
         7.43925170e-01, -2.53176612e-01, -1.37967705e+00,
         7.87643319e-01],
       [ 1.77270449e-01, -7.51084303e-01,  1.00053687e+00,
         8.50050170e-01,  1.35122384e+00, -1.37967705e+00,
         1.62593894e+00],
       [-3.87250911e-01, -7.20170796e-01,  1.71737173e+00,
         1.33878524e+00,  3.36609950e-01, -1.37967705e+00,
         1.34650707e+00],
       [ 1.20520487e+00, -6.40908753e-01,  2.07578916e+00,
         1.65778847e+00,  1.00094571e+00, -1.37967705e+00,
         1.34650707e+00],
       [ 1.07039379e+00, -6.40908753e-01, -7.91550275e-01,
        -1.18111315e+00, -1.64316858e+00, -1.37967705e+00,
         7.87643319e-01],
       [ 8.17623036e-01, -5.12744900e-01, -1.14996770e+00,
         9.50007754e-01,  5.32569026e-01,  7.24807300e-01,
        -6.09516052e-01],
       [-1.68182920e-01,  1.16414755e+00, -1.50838513e+00,
         1.15721524e+00,  7.56970034e-01,  7.24807300e-01,
        -6.09516052e-01],
       [ 3.30918414e-04, -7.39589356e-01,  6.42119443e-01,
         3.40466868e-01, -1.24168891e+00,  7.24807300e-01,
         2.28779571e-01],
       [-1.32250272e+00, -5.57090607e-01,  1.00053687e+00,
         7.54172036e-01, -1.62818581e-02,  7.24807300e-01,
        -8.88947926e-01],
       [-1.01917781e+00, -5.56758459e-01,  2.83702014e-01,
         1.44650381e+00,  1.35127588e+00,  7.24807300e-01,
        -5.06523035e-02],
       [-1.12871180e+00, -3.50904470e-01,  1.35895430e+00,
         1.02460888e-01, -1.63035231e+00, -1.37967705e+00,
         7.87643319e-01],
       [-1.23824580e+00, -7.93665868e-01,  2.83702014e-01,
        -2.44732593e-01,  1.69363179e+00,  7.24807300e-01,
        -3.30084178e-01],
       [-4.20953678e-01,  2.49900590e+00,  1.35895430e+00,
         1.41758296e+00,  1.60295765e+00, -1.37967705e+00,
         7.87643319e-01],
       [-3.87250911e-01,  2.49900590e+00, -1.50838513e+00,
         1.60714581e+00, -1.53967122e+00,  7.24807300e-01,
        -3.30084178e-01],
       [ 1.05354241e+00, -7.26922122e-01, -4.33132845e-01,
         3.41793691e-01, -1.60751727e+00,  7.24807300e-01,
        -6.09516052e-01],
       [-1.17926595e+00, -4.56104839e-01, -1.50838513e+00,
         7.05453317e-01,  1.12726713e+00, -1.37967705e+00,
         1.62593894e+00],
       [-9.43346579e-01, -7.27832300e-01,  1.71737173e+00,
         1.11273492e+00,  8.94530729e-01,  7.24807300e-01,
        -6.09516052e-01],
       [-3.33718493e-02, -7.39589356e-01,  2.83702014e-01,
         7.87474710e-01,  5.65619216e-01,  7.24807300e-01,
        -1.44781167e+00],
       [-1.10343473e+00, -5.60648355e-02, -1.50838513e+00,
         6.82392809e-01,  1.55922297e+00,  7.24807300e-01,
        -6.09516052e-01],
       [ 9.10305648e-01, -5.06858300e-01,  1.00053687e+00,
         3.62852269e-01,  5.89934360e-01,  7.24807300e-01,
        -5.06523035e-02],
       [ 5.08850700e-02,  2.49900590e+00, -1.50838513e+00,
         9.44731624e-01, -1.39837550e+00,  7.24807300e-01,
        -8.88947926e-01],
       [-5.47339058e-01,  1.43297204e-01,  1.35895430e+00,
        -1.48499930e+00,  6.71791601e-01,  7.24807300e-01,
        -5.06523035e-02],
       [ 1.43269855e+00, -5.59405624e-01, -4.33132845e-01,
        -8.07934618e-01,  1.50882133e+00,  7.24807300e-01,
        -5.06523035e-02],
       [ 7.61621459e-02, -5.57090607e-01,  2.83702014e-01,
        -1.35251521e+00,  1.63574183e-01,  7.24807300e-01,
        -6.09516052e-01],
       [-1.41518533e+00, -7.20170796e-01,  1.00053687e+00,
        -1.57452973e+00, -6.23906967e-01,  7.24807300e-01,
        -1.44781167e+00],
       [ 1.58436100e+00,  2.80272578e-01,  1.35895430e+00,
         8.38950025e-03,  5.91451809e-02, -1.37967705e+00,
         1.06707519e+00],
       [ 5.90129354e-01, -4.35202045e-01, -7.47154158e-02,
         1.68082394e+00, -1.44870904e+00, -1.37967705e+00,
         1.06707519e+00],
       [ 1.06196810e+00, -7.41683907e-01,  1.00053687e+00,
        -1.62754638e+00,  1.68764528e+00,  7.24807300e-01,
        -1.44781167e+00],
       [ 9.35582724e-01, -7.13291561e-01,  1.35895430e+00,
         1.69343967e+00,  5.38632569e-01, -1.37967705e+00,
         1.34650707e+00],
       [ 1.01983964e+00,  3.17750972e-01,  1.35895430e+00,
        -4.33376114e-01,  6.22379759e-01, -1.37967705e+00,
         1.06707519e+00],
       [-5.47339058e-01,  5.37427178e-01, -1.50838513e+00,
         1.29479254e+00,  1.26530210e+00,  7.24807300e-01,
         2.28779571e-01],
       [-1.85034304e-01,  2.24226194e+00,  1.71737173e+00,
        -9.24860370e-02,  9.80109615e-01, -1.37967705e+00,
         7.87643319e-01],
       [-7.55003090e-02,  2.80272578e-01,  2.83702014e-01,
         8.03573858e-01, -4.90742755e-01,  7.24807300e-01,
        -1.44781167e+00],
       [-3.70399527e-01, -7.23537311e-01,  6.42119443e-01,
        -5.00550475e-01,  7.82927995e-01,  7.24807300e-01,
        -1.44781167e+00],
       [-1.51331536e-01,  2.83926867e-01, -4.33132845e-01,
        -8.09043556e-01,  1.60451506e+00,  7.24807300e-01,
        -5.06523035e-02],
       [-1.54157071e+00, -4.61431705e-01, -1.50838513e+00,
         5.63296674e-02,  1.39203608e+00,  7.24807300e-01,
        -8.88947926e-01],
       [-8.39260010e-02, -1.86897379e-01,  6.42119443e-01,
        -8.41295399e-01, -1.60798606e+00, -1.37967705e+00,
         7.87643319e-01],
       [ 7.61621459e-02, -4.75954231e-01, -1.14996770e+00,
        -1.21273476e+00,  1.36166453e+00, -1.37967705e+00,
         1.06707519e+00],
       [-6.70746171e-02, -4.72925327e-01,  2.83702014e-01,
         1.47103285e+00,  4.61769767e-01, -1.37967705e+00,
         1.34650707e+00],
       [-1.16241457e+00, -3.91214730e-01, -1.14996770e+00,
        -9.98295772e-01, -1.20707975e+00, -1.37967705e+00,
         1.62593894e+00],
       [-1.85034304e-01, -4.74870197e-01,  2.83702014e-01,
        -1.27897831e+00, -1.37962409e+00, -1.37967705e+00,
         1.34650707e+00],
       [ 6.40683506e-01,  7.18382334e-01,  1.71737173e+00,
         1.65410757e+00, -6.98317965e-01, -1.37967705e+00,
         1.06707519e+00],
       [ 4.97446743e-01,  1.66794177e+00,  2.83702014e-01,
        -1.50683024e+00, -1.41054337e+00, -1.37967705e+00,
         1.06707519e+00],
       [ 1.81185469e+00,  5.37427178e-01,  1.35895430e+00,
         3.60173123e-01, -8.41880687e-01, -1.37967705e+00,
         1.34650707e+00],
       [-1.41518533e+00, -7.17232380e-01, -1.50838513e+00,
         6.14818027e-01, -1.59713092e+00, -1.37967705e+00,
         7.87643319e-01],
       [-6.73724437e-01,  2.49685589e+00, -1.50838513e+00,
        -5.29420806e-01,  1.09137505e+00, -1.37967705e+00,
         7.87643319e-01],
       [-5.72616133e-01,  8.97345597e-01, -7.91550275e-01,
         1.35008464e-02,  3.27205577e-01,  7.24807300e-01,
        -8.88947926e-01],
       [ 2.86804444e-01, -4.18908506e-01,  1.71737173e+00,
        -1.44368977e+00,  1.04419656e-01,  7.24807300e-01,
         2.28779571e-01],
       [ 1.70232069e+00,  6.33202812e-01, -7.47154158e-02,
         1.00154085e+00, -2.71978436e-01, -1.37967705e+00,
         7.87643319e-01],
       [ 1.77270449e-01, -2.04938586e-01, -1.50838513e+00,
         3.04197362e-01, -1.63028720e+00,  7.24807300e-01,
        -6.09516052e-01],
       [ 1.07039379e+00,  1.74506183e+00,  1.71737173e+00,
         1.63869226e+00,  1.00313603e+00,  7.24807300e-01,
        -1.44781167e+00],
       [ 1.63491515e+00,  2.59448929e+00,  1.00053687e+00,
         1.30735860e+00,  1.58526124e+00,  7.24807300e-01,
        -1.16837980e+00],
       [-9.43346579e-01, -6.72942804e-01,  6.42119443e-01,
         3.73572528e-02,  9.14618071e-01,  7.24807300e-01,
        -1.16837980e+00]])

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# initialize the models
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42)
}

# dictionary to hold the evaluation metrics for each model
results = {}

# train and evaluate each model
for name, model in models.items():
    # training the model
    model.fit(X_train_scaled, y_train)

    # making predictions on the test set
    predictions = model.predict(X_test_scaled)

    # calculating evaluation metrics
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    # storing the metrics
    results[name] = {"MAE": mae, "R²": r2}

results_df = pd.DataFrame(results).T  # convert the results to a DataFrame for better readability
print(results_df)

                         MAE        R²
Linear Regression   9.748246  0.529615
Decision Tree      11.760342  0.204962
Random Forest       9.887601  0.509547
Gradient Boosting  10.000117  0.476071